language: emacs-lisp
before_install:
  - curl -fsSkL https://gist.github.com/rejeep/7736123/raw > travis.sh && source ./travis.sh
  - evm install $EVM_EMACS --use --skip
  - cask
env:
  - EVM_EMACS=emacs-24.4-bin
script:
  make travis-ci
